site_name: AppSeed Docs
site_description: Official Documentation | AppSeed
site_url: https://docs.appseed.us/
repo_url: https://github.com/app-generator/docs/
google_analytics: ['UA-104843706-2', 'docs.appseed.us']

markdown_extensions:
  - meta
  - markdown_include.include:
      base_path: docs/common

nav:
- Sections:  
  - 'App Generator'        : '/app-generator/'   
  - 'What Is'              : '/what-is/'   
  - 'How To'               : '/how-to/'   
  - 'Tutorials'            : '/tutorials/'   

- Starters:  
  - 'Admin Dashboards'     : '/admin-dashboards/'   
  - 'Static Sites'         : '/static-site/'   
  - 'JAMstack'             : '/apps/jamstack/'   
  - 'Flask Apps'           : '/apps/flask-apps/'   
  - 'Jinja Templates'      : '/jinja-template/'   

- Boilerplate Code:  
  - 'Index (all starters)'           : '/boilerplate-code/'   
  - 'Flask Boilerplate'              : 'boilerplate-code/flask.md'   
  - 'Flask Dashboard Boilerplate'    : 'boilerplate-code/flask-dashboard.md'   
  - 'Django Boilerplate'             : 'boilerplate-code/django.md'   
  - 'Django Dashboard Boilerplate'   : 'boilerplate-code/django-dashboard.md'   
